### ISSUE TITLE
multipleGroup function relative issues

### ISSUE THREAD

**Issue by seonghobae** [philchalmers/mirt#37] opened 2015-03-02 15:50 UTC
(forwarding from https://groups.google.com/d/msg/mirt-package/JWkCc23LYa4/i9P9aIJP7foJ)

Here is my raw data and code.
https://www.dropbox.com/s/ugym9z4pa25ob8u/entrepreneur%20%28debug%29.tar.gz?dl=0

You may execute line number 1 to 55 and 74 to 148 to reproduce error messages.

--
Seongho Bae

**Comment by philchalmers** [comment] 2015-03-04 03:48
I can't read half of this for format related and other reasons. Could you create a self-contained `.Rdata` file containing the relevant files and a smaller script reproducing the issue? Thanks.

**Comment by seonghobae** [comment] 2015-03-04 04:07
Check this link:

https://www.dropbox.com/sh/z1yv1soyi014kr5/AACvm1DsHZMY8YEICIu9f6q3a?dl=0

(I'm generating a '.Rdata' file, and I'll update as soon as possible via my dropbox.)

**Comment by philchalmers** [comment] 2015-03-04 15:25
This seems to be working better, thanks. I'll let you know what I find.

**Comment by philchalmers** [comment] 2015-03-04 17:15
Fixed the issue (wasn't protecting the NR updating from intercept crossing in the MHRM), but I honestly don't think this model is empirically identified; the huge number of iterations is a good indication of that. Instead of the old error, I now get a parameter update error that the completely data Hessian becomes NPD. I honestly think the sample size is just too small for this model, especially for multidimensional DIF testing.

**Comment by seonghobae** [comment] 2015-03-04 21:50
Thanks, Phil!

I was previously know it what sample size was too small to estimate parameters for the multiple group analysis. But, I can not get more data points over 263 even I was tried to collect more within 2 years. Population may be too small, so I apologize it to make concern. I'll check new result with new dev version. Cheers.

--
Seongho Bae

**Comment by philchalmers** [comment] 2015-03-05 18:13
No problem. Just close the issue later if you are satisfied, otherwise keep posting if something else comes up in the code. Cheers.

**Comment by seonghobae** [comment] 2015-03-15 05:39
![default](https://cloud.githubusercontent.com/assets/8172694/6654812/d075342c-cb20-11e4-8d75-362280be3fd8.png)

I encountered an error with DIF testing what include parameter d. Is It related to sample sizes?

**Comment by philchalmers** [comment] 2015-03-15 14:35
Yes, there isn't enough information available to keep the Hessian stable (not positive definite), so it couldn't be inverted. Completely related to sample size

**Comment by philchalmers** [comment] 2015-03-16 00:39
Try it with the commit pushed today. Newton-Raphson updates now use pseudo-inverse when the Hessian is ill-conditioned, so that should help get the model parameters away from bad starting locations.

**Comment by seonghobae** [comment] 2015-03-16 16:47
Okay, I trying to extract DIF results with 'drop_sequential' scheme on my MacBook. I'll give feedback to you if that finish abnormally.

Anyway, I still failing to extract DIF with 'add_seqential' scheme,
![default](https://cloud.githubusercontent.com/assets/8172694/6671048/feeaa366-cc45-11e4-8f5e-a20d79df7808.PNG)

Missing variable names on a summary of Multigroup CFA analysis,
![default](https://cloud.githubusercontent.com/assets/8172694/6671090/4dacbbb0-cc46-11e4-82b8-5278eba51134.PNG)

And Missing loadings and communality values on summary for context of the multiple-group CFA analysis even If  I can check loadings and communality normally on summary for the single group CFA analysis in any data I can test.
![default](https://cloud.githubusercontent.com/assets/8172694/6671149/bf41d742-cc46-11e4-84c6-d95aa6359959.PNG)
![default](https://cloud.githubusercontent.com/assets/8172694/6671221/39b9d0f6-cc47-11e4-9e6f-a0dbf752bc40.PNG)

**Comment by philchalmers** [comment] 2015-03-16 20:28
If there are no loadings for a particular item then there is no need to have it in your model (which is probably what `DIF()` is complaining about). Just remove the 24th item and refit your model, then pass that object instead.

**Comment by seonghobae** [comment] 2015-03-18 15:42
No, That is the bug.

See this image.
![syntax](https://cloud.githubusercontent.com/assets/8172694/6712476/21429258-cdd0-11e4-93ea-5b40c90fcd3b.PNG)
![cfa1](https://cloud.githubusercontent.com/assets/8172694/6712448/f60ea1c6-cdcf-11e4-84dd-0a543c15b66d.PNG)

In the Single class, Match correctly among syntax and CFA results. But in the Multiple class analysis, It doesn't match with syntax and CFA results
![syntax](https://cloud.githubusercontent.com/assets/8172694/6712476/21429258-cdd0-11e4-93ea-5b40c90fcd3b.PNG)
![cfa2](https://cloud.githubusercontent.com/assets/8172694/6712568/8dd07e6c-cdd0-11e4-85c4-37c507247bf4.PNG)
![cfa3](https://cloud.githubusercontent.com/assets/8172694/6712578/9dec281e-cdd0-11e4-9b78-706791f1b885.PNG)

Please check out this.

**Comment by philchalmers** [comment] 2015-03-18 16:29
I can't reproduce this. Perhaps something else is going on? Example code reproducing this exact problem would be helpful.

**Comment by seonghobae** [comment] 2015-03-18 17:55
Yes, I'm improving my model after your comments about the validity, so something else is going on.
But, I'm retrying to estimate coefficients using another system for reproducing the bug. I have four various systems (Mac, Windows 7, Windows 8, Ubuntu Linux), I have to cross-check it; sometimes one of my systems is returning abnormal results by unknown system's problems. I'll update sample code and sample data ASAP if I can reproduce the bug on another system. Cheers.

**Comment by seonghobae** [comment] 2015-03-18 18:56
I update sample codes and data.

Data: https://www.dropbox.com/s/7hpdgprtbe5s6ew/multiGroup_debug.Rdata?dl=0
Code: https://www.dropbox.com/s/v1epoa14qbs0nwt/multiGroup_debug.R?dl=0

I fail to reproduce the bug; that may unknown problem of the specific system; All things are okay.
But, I still fail to use the 'add_sequential' method even all coefficients can print by the summary method.
![default](https://cloud.githubusercontent.com/assets/8172694/6716871/b40185ac-cdeb-11e4-8cc2-0278fa3666f2.PNG)

Please check it.

**Comment by philchalmers** [comment] 2015-03-18 20:53
You don't want `add_sequential` here, you want `drop_sequential`. The scheme refers to where constrains are added or dropped, and in your model the constraints are already in the model (you set them equal across groups in your input model), and therefore you want to 'drop' them to test for DIF.

**Comment by seonghobae** [comment] 2015-03-19 05:22
Okay, I got it! Thanks!

**Comment by seonghobae** [comment] 2015-03-20 07:34
One more question!

I had a question five dayes ago (https://github.com/philchalmers/mirt/issues/37#issuecomment-80868608), You made patches for the problem.

But, I tried today, It failed.
![syntax2](https://cloud.githubusercontent.com/assets/8172694/6747524/f01083c6-cf1d-11e4-87b3-adf115b8ae84.PNG)

I want to know your opinion. My data can't make a test for Differential Item Testing or Differential Test functioning causes small sample problems?

--
Seongho

**Comment by philchalmers** [comment] 2015-03-20 12:55
Definitely not DTF (I haven't really developed the theory for that yet anyway in MIRT models), but DIF you still could. I just don't think `drop_sequential` is the way to go with the models being so unstable. 

I would just use `drop`, check where differences occur, refit a new baseline model given the previous DIF information, and repeat again with a new subset using the `items2test` argument in `DIF()`. It's like manually doing a drop sequential scheme, but you can see where the model starts to crash and why (the `dgesdd` error is really bad, meaning the svd algorithm failed to converge).

**Closed** 2015-03-23 20:35 UTC
