### ISSUE TITLE
Longitudinal IRT with latent regression

### ISSUE THREAD

**Issue by CJangelo** [philchalmers/mirt#156] opened 2019-04-12 15:14 UTC
Hi Phil, 
I’m a big fan of your mirt R package, and very grateful for all the support you provide. However, it seems like FlexMIRT can recover the generating parameters from my model but mirt cannot. 

Details:
1. Longitudinal IRT model with a latent regression
2. The coefficient in the latent regression was recovered in FlexMIRT but not in R. 
They should be (0, 0.5, 1.0, 1.5). 
3. I have attached:
a. R code to generate data
b. R code to fit model to the generated data
c. R model output saved as .rds file 
as well as the
d. data prepped for flexmirt 
e. flexmirt code
f. flexmirt output

Notice the difference in the latent regression coefficients:
FlexMIRT
Latent Regression Coefficients:

   Group  1: Ref
                   Covariate  1
             P#    Beta    s.e.
Theta  1     38   -0.01    0.01
Theta  2     39    0.50    0.02
Theta  3     40    0.96    0.02
Theta  4     41    1.48    0.02

$lr.betas
F1_(Intercept) F1_TXA F2_(Intercept) F2_TXA F3_(Intercept) F3_TXA F4_(Intercept) F4_TXA
par                  0 -0.248              0     0.271             0  	   0.803              0  1.358
CI_              NA -0.265             NA  0.261           NA    NaN          NA  1.336
CI_              NA -0.231              NA  0.280          NA    NaN          NA  1.379
[compare_flexmirt_04122019.zip](https://github.com/philchalmers/mirt/files/3073926/compare_flexmirt_04122019.zip)

**Comment by philchalmers** [comment] 2019-04-13 02:10
This looks like it has something to do with the missing data. When the original dataset without the missingness is used the estimates appear unbiased given the population generating functions. 

Was there anything special about this missingness pattern that could have modified the underlying structure? It's odd that flexmirt and mirt are different here, but it's even more odd that mirt is providing higher log-likelihood estimates (hence, the parameters found may actually be more likely than flexmirt's....despite the fact that they seem to be biased in this case).

**Comment by philchalmers** [comment] 2019-04-13 03:00
Actually, it seems to be the case that these latent regression betas are relatively uncertain. Consider the following

```r
 mod <- mixedmirt(data=data, model = mod.struc, itemtype='graded',
+                   covdata=Z, lr.fixed = ~ TXA,
+                     constrain = constraints, SE = F)
Stage 3 = 14, LL = -240987.8, AR(0.89) = [0.11], gam = 0.0260, Max-Change = 0.0008

Calculating log-likelihood...
> mod

Call:
mixedmirt(data = data, covdata = Z, model = mod.struc, itemtype = "graded", 
    lr.fixed = ~TXA, constrain = constraints, SE = F)

Full-information item factor analysis with 4 factor(s).
Converged within 0.001 tolerance after 14 MHRM iterations.
mirt version: 1.30.4 
M-step optimizer: NR1 
Latent density type: Gaussian 

Log-likelihood = -213724.3, SE = 0.182
Estimated parameters: 116 
AIC = 427530.5; AICc = 427530.9
BIC = 427826.2; SABIC = 427695.9
> coef(mod)$lr.betas
        F1_(Intercept)     F1_TXA F2_(Intercept)    F2_TXA F3_(Intercept)   F3_TXA F4_(Intercept)  F4_TXA
par                  0 -0.2479056              0 0.2706955              0 0.802801              0 1.35757
CI_2.5             NaN        NaN            NaN       NaN            NaN      NaN            NaN     NaN
CI_97.5            NaN        NaN            NaN       NaN            NaN      NaN            NaN     NaN
> 
> set.seed(1234)
> mod1234 <- mixedmirt(data=data, model = mod.struc, itemtype='graded', GenRandomPars=TRUE,
+                  covdata=Z, lr.fixed = ~ TXA,
+                  constrain = constraints, SE = F)
Stage 3 = 12, LL = -241766.3, AR(0.89) = [0.12], gam = 0.0294, Max-Change = 0.0006

Calculating log-likelihood...
> mod1234

Call:
mixedmirt(data = data, covdata = Z, model = mod.struc, itemtype = "graded", 
    lr.fixed = ~TXA, constrain = constraints, SE = F, GenRandomPars = TRUE)

Full-information item factor analysis with 4 factor(s).
Converged within 0.001 tolerance after 12 MHRM iterations.
mirt version: 1.30.4 
M-step optimizer: NR1 
Latent density type: Gaussian 

Log-likelihood = -213649.9, SE = 0.182
Estimated parameters: 116 
AIC = 427381.8; AICc = 427382.2
BIC = 427677.5; SABIC = 427547.2
> coef(mod1234)$lr.betas
        F1_(Intercept)     F1_TXA F2_(Intercept)    F2_TXA F3_(Intercept)  F3_TXA F4_(Intercept)   F4_TXA
par                  0 0.03703597              0 0.5829568              0 1.12366              0 1.697864
CI_2.5             NaN        NaN            NaN       NaN            NaN     NaN            NaN      NaN
CI_97.5            NaN        NaN            NaN       NaN            NaN     NaN            NaN      NaN
> 
> set.seed(1)
> mod1 <- mixedmirt(data=data, model = mod.struc, itemtype='graded', GenRandomPars=TRUE,
+                      covdata=Z, lr.fixed = ~ TXA,
+                      constrain = constraints, SE = F)
Stage 3 = 12, LL = -241881.3, AR(0.89) = [0.13], gam = 0.0294, Max-Change = 0.0007

Calculating log-likelihood...
> mod1

Call:
mixedmirt(data = data, covdata = Z, model = mod.struc, itemtype = "graded", 
    lr.fixed = ~TXA, constrain = constraints, SE = F, GenRandomPars = TRUE)

Full-information item factor analysis with 4 factor(s).
Converged within 0.001 tolerance after 12 MHRM iterations.
mirt version: 1.30.4 
M-step optimizer: NR1 
Latent density type: Gaussian 

Log-likelihood = -213626.6, SE = 0.182
Estimated parameters: 116 
AIC = 427335.1; AICc = 427335.5
BIC = 427630.7; SABIC = 427500.4
> coef(mod1)$lr.betas
        F1_(Intercept)      F1_TXA F2_(Intercept)    F2_TXA F3_(Intercept)   F3_TXA F4_(Intercept)   F4_TXA
par                  0 -0.06067116              0 0.4843652              0 1.029758              0 1.599402
CI_2.5             NaN         NaN            NaN       NaN            NaN      NaN            NaN      NaN
CI_97.5            NaN         NaN            NaN       NaN            NaN      NaN            NaN      NaN
```

I'm not sure if flexmirt's defaults of using a thinning of 10 versus mirt's thinning of 5 makes a big difference here, but you could try that to see if it fixes the problem.

**Comment by CJangelo** [comment] 2019-04-14 19:56
Thanks for the reply, Phil. I tried increasing the MH draws to 10, then 20 (technical = list(MHDRAWS = 20)). It doesn't seem to resolve the bias in the estimated latent regression parameters (see below). 

1. What's odd is that the change between time =1 and time=4 is recovered almost perfectly, i.e., generating values of 0.0 and 1.5 for a difference of 1.5, and estimated values of -0.1904504 and 1.319357 for a difference of 1.509807. 

2. Furthermore, the slopes, and the var/covar matrix are all recovered very well. 

3. The bias is just in the intercepts and the latent regression betas. Everything is shifted over. **Does FlexMIRT constrain something behind the scenes and I'm not doing that in mirt?** 

4. Is it just that the likelihoods are flat and I'm finding local optimums, as in your previous comment about GenRandomPars = TRUE? Would you consider it best-practices to always fit complicated models like these with multiple starting values and check convergence that way? 

5. Does it concern you at all that the estimates are heavily biased in spite of the fact that this is generated data with only covariate in the latent regression and N=7k at timepoint 4 (MCAR drop out mechanism)? It certainly makes me nervous about using these models with empirical data. 

Thanks again



out <- GenerateMissingData(random.seed = 4142019, P.drop.inter=-2, P.drop.slope.Z = 0)
data <- out$X.miss
Z <- data.frame(out$Z)
...

> mod20

Call:
mixedmirt(data = data, covdata = Z, model = mod.struc, itemtype = "graded", 
    lr.fixed = ~TXA, constrain = constraints, SE = T, technical = list(MHDRAWS = 20), 
    SE.type = "MHRM")

Full-information item factor analysis with 4 factor(s).
Converged within 0.001 tolerance after 11 MHRM iterations.
mirt version: 1.29.3 
M-step optimizer: NR1 
Latent density type: Gaussian 

Information matrix estimated with method: MHRM
Condition number of information matrix = 5161.283
Second-order test: model is not a maximum, or the information matrix is too inaccurate

Log-likelihood = -212661.7, SE = 0.182
Estimated parameters: 116 
AIC = 425405.4; AICc = 425405.7
BIC = 425701; SABIC = 425570.7


> coef(mod20)$lr.betas
        F1_(Intercept)     F1_TXA F2_(Intercept)    F2_TXA F3_(Intercept)    F3_TXA F4_(Intercept)   F4_TXA
par                  0 -0.1904504              0 0.3026981              0 0.8270127              0 1.319357
CI_2.5              NA -0.2539393             NA 0.2390474             NA 0.8048419             NA 1.263834
CI_97.5             NA -0.1269616             NA 0.3663488             NA 0.8491835             NA 1.374880
>

**Comment by philchalmers** [comment] 2019-04-16 03:22
I looked into this a little more. Turns out it is two issues: a local minimum, and a bug in mirt. 

I change the starting values for the item intercept parameters, fixed the MEANS to 0, and estimated the latent intercepts instead (equivalent approach). This gave more what I was expecting.

```r
mod.struc2 <- 'F1 = 1-5,
                F2 = 6-10,
F3 = 11-15,
F4 = 16-20,
COV = F2*F2, F3*F3, F4*F4,
F1*F2, F1*F3, F1*F4,
F2*F3, F2*F4,
F3*F4'

sv <- mixedmirt(data=data, model = mod.struc2, itemtype='graded',
                covdata=Z, lr.fixed = ~ TXA, pars = 'values')
sv$est[c(177:182)] <- TRUE

sv$value[sv$name %in% c('d1', 'd2', 'd3', 'd4')] <- c(2,1,-1,-2)

mod2 <- mixedmirt(data=data, model = mod.struc2, itemtype='graded',
                  covdata=Z, lr.fixed = ~ TXA, draws=2, pars=sv,
                    constrain = constraints, SE = F)

coef(mod2)

 .... 

$GroupPars
    MEAN_1 MEAN_2 MEAN_3 MEAN_4 COV_11 COV_21 COV_31 COV_41 COV_22 COV_32 COV_42 COV_33 COV_43 COV_44
par      0      0      0      0      1  0.815    0.5   0.24  1.217  0.725  0.347  1.352  0.644  1.583

$lr.betas
    F1_(Intercept) F1_TXA F2_(Intercept) F2_TXA F3_(Intercept) F3_TXA F4_(Intercept) F4_TXA
par              0  0.006          0.003  0.541          0.045  1.032         -0.021  1.662
```

Regarding the bug, it seems in your original approach the MEANS input were never actually used in the model, and were only estimated passively in that they did not get included in the stochastic draws. This should be fixed now on the dev version. For now, I'd probably just stick with the latent regression intercept approach with better starting values.

**Comment by CJangelo** [comment] 2019-04-16 13:54
It didn't even occur to me to just free the intercepts instead of the means. Thanks.

1. I checked this and it seems that the starting values really do make a big difference, even when estimating intercepts instead of means (sv$est[177:182] <- TRUE) and when using 10 draws (technical = list(MHDRAWS = 10)).

with usual starting values:
$lr.betas
        F1_(Intercept) F1_TXA F2_(Intercept) F2_TXA F3_(Intercept) F3_TXA F4_(Intercept) F4_TXA
par                  0 -0.297         -0.106  0.291         -0.144   0.86         -0.256   1.49


with the better starting values (i.e., sv$value[sv$name %in% c('d1', 'd2', 'd3', 'd4')] <- c(2,1,-1,-2)):

$lr.betas
        F1_(Intercept) F1_TXA F2_(Intercept) F2_TXA F3_(Intercept) F3_TXA F4_(Intercept) F4_TXA
par                  0  0.032          0.001  0.536          0.052  1.041          0.011  1.621


2. It seems to me like a big take-away from this is to check very thoroughly for local minimums by using GenRandomPars.  This requires a lot more attention that I've given it in the past. 

Thanks again for this very productive exchange.

**Comment by philchalmers** [comment] 2019-04-16 15:33
I think the problem with your simulation setting was that the intercept ends were a little on the wide side, so setting up starting values for the intercept parameters made a big difference. Of course, there was a bug that you did ultimately encounter, so it's good that you brought this to my attention nonetheless. I'll close this issue for now since I think it is resolved, but if you find additional problem feel free to re-open.

**Closed by philchalmers** 2019-04-16 15:33 UTC
